-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- 主機： 127.0.0.1
-- 產生時間： 2025-02-27 15:45:32
-- 伺服器版本： 10.4.32-MariaDB
-- PHP 版本： 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- 資料庫： `daiski_db`
--

-- --------------------------------------------------------

--
-- 資料表結構 `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` int(11) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `gender` tinyint(4) NOT NULL DEFAULT 0,
  `introduction` text DEFAULT NULL,
  `specIntroduction` text DEFAULT NULL,
  `createdAt` datetime NOT NULL DEFAULT current_timestamp(),
  `publishAt` datetime DEFAULT NULL,
  `unpublishAt` datetime DEFAULT NULL,
  `deleteAt` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- 傾印資料表的資料 `products`
--

INSERT INTO `products` (`id`, `name`, `price`, `category_id`, `gender`, `introduction`, `specIntroduction`, `createdAt`, `publishAt`, `unpublishAt`, `deleteAt`) VALUES
(1, 'Dimito VTX OG Temp Jacket 智能加熱滑雪外套 - Black', 15400, 17, 3, 'Waterproof : 20K / Breathability : 15K\r\nDitex 布料具有一流的抗水性和防水/透氣性能\r\n溫度控制系統（TCS），可透過輔助電池供電在內部產生熱量 ( 外套背部與胸部處設有加熱區 )\r\n用於連接口袋內 USB TYPE-C 型行動電池的傳輸線\r\n採用 Primaloft 科技羽絨保暖材質，具有高耐寒性與保暖，超輕量材質\r\n寬鬆版型，寬鬆舒適\r\nYKK® 防水拉鍊\r\n拉鍊插手口袋及中央對角拉鍊雙向設計\r\n領口處氣孔設計，呼吸舒適\r\n手臂處通行證口袋\r\n內部雪鏡網袋及內部拉鍊手機置物口袋\r\n腋下拉鍊透氣孔\r\n風帽及下擺有抽繩設計調整鬆緊\r\n可拆卸式雪裙可防止滑行時粉雪侵入\r\n魔鬼氈可調式袖口\r\n萊卡指套設計\r\n左胸飾有運動刺繡藝術設計', '表面布料 : 尼龍 100% \r\n襯裡(1)：尼龍 100%\r\n襯裡(2)：聚酯纖維 100%\r\n保暖層 : 聚酯纖維 100%', '2025-02-21 10:45:19', NULL, '2025-02-26 18:12:27', NULL),
(2, 'Dimito VTX OG Temp Jacket 智能加熱滑雪外套 - Teal Green', 15400, 17, 3, 'Waterproof : 20K / Breathability : 15K\nDitex 布料具有一流的抗水性和防水/透氣性能\n溫度控制系統（TCS），可透過輔助電池供電在內部產生熱量 ( 外套背部與胸部處設有加熱區 )\n用於連接口袋內 USB TYPE-C 型行動電池的傳輸線\n採用 Primaloft 科技羽絨保暖材質，具有高耐寒性與保暖，超輕量材質\n寬鬆版型，寬鬆舒適\nYKK® 防水拉鍊\n拉鍊插手口袋及中央對角拉鍊雙向設計\n領口處氣孔設計，呼吸舒適\n手臂處通行證口袋\n內部雪鏡網袋及內部拉鍊手機置物口袋\n腋下拉鍊透氣孔\n風帽及下擺有抽繩設計調整鬆緊\n可拆卸式雪裙可防止滑行時粉雪侵入\n魔鬼氈可調式袖口\n萊卡指套設計\n左胸飾有運動刺繡藝術設計', '表面布料 : 尼龍 100% \n襯裡(1)：尼龍 100%\n襯裡(2)：聚酯纖維 100%\n保暖層 : 聚酯纖維 100%', '2025-02-21 11:42:36', '2025-02-26 16:07:01', NULL, NULL),
(3, 'Dimito VTX OG Temp Jacket 智能加熱滑雪外套 - Slate Blue', 15400, 17, 3, 'Waterproof : 20K / Breathability : 15K\r\nDitex 布料具有一流的抗水性和防水/透氣性能\r\n溫度控制系統（TCS），可透過輔助電池供電在內部產生熱量 ( 外套背部與胸部處設有加熱區 )\r\n用於連接口袋內 USB TYPE-C 型行動電池的傳輸線\r\n採用 Primaloft 科技羽絨保暖材質，具有高耐寒性與保暖，超輕量材質\r\n寬鬆版型，寬鬆舒適\r\nYKK® 防水拉鍊\r\n拉鍊插手口袋及中央對角拉鍊雙向設計\r\n領口處氣孔設計，呼吸舒適\r\n手臂處通行證口袋\r\n內部雪鏡網袋及內部拉鍊手機置物口袋\r\n腋下拉鍊透氣孔\r\n風帽及下擺有抽繩設計調整鬆緊\r\n可拆卸式雪裙可防止滑行時粉雪侵入\r\n魔鬼氈可調式袖口\r\n萊卡指套設計\r\n左胸飾有運動刺繡藝術設計', '表面布料 : 尼龍 100% \r\n襯裡(1)：尼龍 100%\r\n襯裡(2)：聚酯纖維 100%\r\n保暖層 : 聚酯纖維 100%', '2025-02-21 11:46:41', NULL, NULL, NULL),
(4, 'Volcom Iguchi Slack Vest 滑雪機能背心 - Black', 14000, 4, 1, '當您在惡劣的氣候條件下遊覽世界上最好的 BC 地區時，您需要一個可以為您提供支援的裝備。\r\nIguchi Slack 機能背心為重要的必需品提供了大量存儲空間，配有探針套、雪鏟置物口袋和外部雪鏟刀片架，以及 Guide Proven 無線電胸袋。\r\n齊全的設計由 BC 地區創新者和我們的常駐導遊 Bryan Iguchi 設計和測試，作為他的指標性系列的一部分，替您在雪地上會遇上的任何情況提供免提功能。', 'Features\r\n\r\nMen\'s snow jacket\r\nWaterproof/Breathability Rating: 15,000mm / 15,000gm²\r\nV-Science 2-Layer\r\nV-Science Supreme Twill with Non-Fluorinated DWR\r\n80/60g Insulation\r\nCritical Taped Seams\r\n91 Fit\r\nZip Tech® Jacket to Pant Interface\r\nRemovable Hinged Hood Styling\r\nHidden Toggle Cinch Hood\r\nSuper Suede Chin Guard\r\nMesh Lined Zippered Vents\r\nAdjustable Powder Skirt\r\nV-Science 2 Way Cuff System\r\nLeft Sleeve Zippered Pass Pocket\r\nBrushed Tricot Lined Handwarmer Pockets\r\nPocket Access Hem Cinch\r\nSpecialty Ticket Ring\r\nWhistle Zipper Pull\r\n100% NYLON (POLYAMIDE)', '2025-02-21 11:46:41', NULL, NULL, NULL),
(5, '686 Men\'s Gore-tex 3L ATV Jacket 滑雪外套 - Dusty Yellow', 24000, 4, 1, '所有地形、所有條件、所有季節 - ATV ( All-Terrain Vehicle )\r\n在滑雪方面，Gigi Rüf 沒有特定的滑行偏好，因此我們打造了他夢想中的裝備。他想要一款外觀前衛的滑雪外套，採用輕質 Gore-Tex 3 層面料製成，具有更高的耐用性和終極性能，不僅適合滑雪渡假村的造型，還適合野雪的起伏和極端環境。\r\nATV 滑雪外套設計為適合全地形滑手的一件式夾克。', '三層 bluesign®  Approved GORE-TEX 聚酯纖維面料 + DWR 防潑水技術處理\r\n附有雪崩安全卡\r\n附護目拭鏡布\r\nShell Design\r\n全接縫線 GORE-TEX 膠條 (壓膠) 處理\r\nAir-Flo™ 腋下拉鍊通風孔\r\n可調節頭套兼容安全帽\r\nHood Link 包裹收納系統\r\n美麗諾羊毛內領 / 口水布\r\n手機保溫口袋\r\n防纏結耳機環\r\n內部護目鏡網袋 + 鏡片暗袋\r\nGlove Link™ 內拇指握把\r\n內部 Lycra 彈性指套\r\n帶鑰匙夾的拉鍊袖口口袋\r\n帶鑰匙夾的胸前口袋\r\n可調節魔鬼氈袖口\r\n萊卡彈性可調節雪裙\r\n隱藏式可調節下擺束帶\r\n中央前部、腋下通風口和胸部拉鍊使用防水拉鍊\r\n雪衣褲連接系統\r\n內部口袋數量：3、外部口袋數量：5', '2025-02-23 13:20:02', '2025-02-26 15:52:24', NULL, NULL),
(6, '686 Men\'s Gore-tex 3L ATV Jacket 滑雪外套 - Black', 24000, 4, 1, '所有地形、所有條件、所有季節 - ATV ( All-Terrain Vehicle )\r\n在滑雪方面，Gigi Rüf 沒有特定的滑行偏好，因此我們打造了他夢想中的裝備。他想要一款外觀前衛的滑雪外套，採用輕質 Gore-Tex 3 層面料製成，具有更高的耐用性和終極性能，不僅適合滑雪渡假村的造型，還適合野雪的起伏和極端環境。\r\nATV 滑雪外套設計為適合全地形滑手的一件式夾克。', '三層 bluesign®  Approved GORE-TEX 聚酯纖維面料 + DWR 防潑水技術處理\r\n附有雪崩安全卡\r\n附護目拭鏡布\r\nShell Design\r\n全接縫線 GORE-TEX 膠條 (壓膠) 處理\r\nAir-Flo™ 腋下拉鍊通風孔\r\n可調節頭套兼容安全帽\r\nHood Link 包裹收納系統\r\n美麗諾羊毛內領 / 口水布\r\n手機保溫口袋\r\n防纏結耳機環\r\n內部護目鏡網袋 + 鏡片暗袋\r\nGlove Link™ 內拇指握把\r\n內部 Lycra 彈性指套\r\n帶鑰匙夾的拉鍊袖口口袋\r\n帶鑰匙夾的胸前口袋\r\n可調節魔鬼氈袖口\r\n萊卡彈性可調節雪裙\r\n隱藏式可調節下擺束帶\r\n中央前部、腋下通風口和胸部拉鍊使用防水拉鍊\r\n雪衣褲連接系統\r\n內部口袋數量：3、外部口袋數量：5', '2025-02-23 13:23:54', NULL, NULL, NULL),
(7, '686 Women\'s Athena Insulated Jacket 滑雪外套 - Black Ghost Floral', 7400, 5, 2, '當我們在最喜歡的雪場滑行時，Athena 滑雪外套讓我們看起來更時尚且舒適。\r\n堅固的結構和技術面料意味著您已經為冬季冒險做好了準備，接縫壓膠和 infiDRY® 10K 防水面料可防止您被淋濕，並且整個隔熱層可讓您在纜車上依舊保持溫暖。', '10,000MM 防水/10,000mm 透氣等級 + DWR 防潑水技術處理\r\n雙層 infiDRY® 10K 專利防水彈力面料 + DWR 防潑水技術處理\r\nInfiLOFT® Insulation 隔熱材料 ( 80g 身體, 60g袖子, 40g頭套 )\r\n關鍵部位接縫線膠條 (壓膠) 處理\r\nAir-Flo™ 網狀拉鍊內側通風口\r\n可調節頭套兼容安全帽\r\n手機保暖口袋\r\nGlove Link™ 內拇指握把\r\n針織抓絨內領 / 口水布\r\n686 印花內部護目鏡 + 鏡片暗袋\r\n防纏結耳機環\r\n可調節魔鬼氈袖口\r\n帶鑰匙夾的全閉合袖口口袋\r\n帶鑰匙夾的前插手口袋\r\n可調節下擺收緊設計\r\n可調節雪裙\r\n雪衣褲連接系統', '2025-02-23 13:32:14', NULL, NULL, NULL),
(8, '686 Women\'s Upton Anorak 半開襟式滑雪外套 - Limestone', 7400, 5, 2, '如果復古夾克的性能和外觀一樣優秀就好了。\r\n我們通過將時尚和技術功能融合到 Upton Anorak 中，讓夢想成為現實，這款夾克以我們一件復古單品為基礎，融入了現代剪裁和功能性。', '10,000MM 防水/10,000mm 透氣等級 + DWR 防潑水技術處理\r\n雙層 infiDRY® 10K 專利防水面料 + DWR 防潑水技術處理\r\nInfiLOFT® Insulation 隔熱材料\r\n關鍵部位的縫線膠條 (壓膠) 處理\r\n側拉鍊開口，帶雙向拉鍊，用於通風透氣\r\n可調節頭套兼容安全帽\r\n手機保溫口袋帶耳機線孔\r\nHood Link 包裹收納系統\r\n防纏結耳機環\r\n內部護目鏡 + 鏡片暗袋\r\nGlove Link™ 內拇指握把\r\n可調節魔鬼氈袖口\r\n內部 Lycra 彈性指套\r\n帶鑰匙夾的魔鬼氈袖口口袋\r\n帶鑰匙夾的前插手口袋\r\n可調節雪裙\r\n可調節下擺收緊設計\r\n雪衣褲連接系統', '2025-02-23 13:36:11', NULL, NULL, NULL),
(9, '686 Women\'s Upton Anorak 半開襟式滑雪外套 - Cypress Green', 7400, 5, 2, '如果復古夾克的性能和外觀一樣優秀就好了。\r\n我們通過將時尚和技術功能融合到 Upton Anorak 中，讓夢想成為現實，這款夾克以我們一件復古單品為基礎，融入了現代剪裁和功能性。', '10,000MM 防水/10,000mm 透氣等級 + DWR 防潑水技術處理\r\n雙層 infiDRY® 10K 專利防水面料 + DWR 防潑水技術處理\r\nInfiLOFT® Insulation 隔熱材料\r\n關鍵部位的縫線膠條 (壓膠) 處理\r\n側拉鍊開口，帶雙向拉鍊，用於通風透氣\r\n可調節頭套兼容安全帽\r\n手機保溫口袋帶耳機線孔\r\nHood Link 包裹收納系統\r\n防纏結耳機環\r\n內部護目鏡 + 鏡片暗袋\r\nGlove Link™ 內拇指握把\r\n可調節魔鬼氈袖口\r\n內部 Lycra 彈性指套\r\n帶鑰匙夾的魔鬼氈袖口口袋\r\n帶鑰匙夾的前插手口袋\r\n可調節雪裙\r\n可調節下擺收緊設計\r\n雪衣褲連接系統', '2025-02-23 13:39:29', NULL, NULL, NULL),
(10, 'Dimito VTX OG 2L Pants 滑雪褲 - Teal Green', 7400, 18, 3, 'Waterproof : 15K / Breathability : 10K\r\n兩側主插手口袋立體剪裁設計\r\n標準版型與寬鬆版型\r\n褲管腳跟處防磨耐用設計\r\nYKK® 金屬防水拉鍊\r\n可調式腰帶設計\r\n胯下拉鍊透氣孔\r\n腰部雪裙可防止粉雪侵入\r\n褲管內雪裙設計\r\n可調式褲管抽繩設計', '表面布料 : 尼龍 100%\r\n襯裡(1)：尼龍 100%\r\n襯裡(2)：聚酯纖維 100%', '2025-02-23 13:45:07', NULL, NULL, NULL),
(11, 'Dimito VTX OG 2L Pants 滑雪褲 - Mist Blue', 7400, 18, 3, 'Waterproof : 15K / Breathability : 10K\r\n兩側主插手口袋立體剪裁設計\r\n標準版型與寬鬆版型\r\n褲管腳跟處防磨耐用設計\r\nYKK® 金屬防水拉鍊\r\n可調式腰帶設計\r\n胯下拉鍊透氣孔\r\n腰部雪裙可防止粉雪侵入\r\n褲管內雪裙設計\r\n可調式褲管抽繩設計', '表面布料 : 尼龍 100%\r\n襯裡(1)：尼龍 100%\r\n襯裡(2)：聚酯纖維 100%', '2025-02-23 13:48:12', NULL, NULL, NULL),
(12, 'Dimito VTX OG 2L Pants 滑雪褲 - Fuchsia Red', 9200, 18, 3, 'Waterproof : 15K / Breathability : 10K\r\n兩側主插手口袋立體剪裁設計\r\n標準版型與寬鬆版型\r\n褲管腳跟處防磨耐用設計\r\nYKK® 金屬防水拉鍊\r\n可調式腰帶設計\r\n胯下拉鍊透氣孔\r\n腰部雪裙可防止粉雪侵入\r\n褲管內雪裙設計\r\n可調式褲管抽繩設計', '表面布料 : 尼龍 100%\r\n襯裡(1)：尼龍 100%\r\n襯裡(2)：聚酯纖維 100%', '2025-02-23 13:51:29', NULL, NULL, NULL),
(13, '686 Men\'s Standard Shell Pant 滑雪褲 - Charcoal', 4400, 7, 1, '686 的基本款滑雪褲採用時尚的黑色配色，防水等級為 10K，為山區的惡劣條件提供有力的保護。而大腿內側的 Air-flo 網狀通風孔可在你感到悶熱時讓冷空氣進入調節。', '10,000MM 防水等級 + DWR 防潑水技術處理\r\ninfiDRY® 10K 專利防水面料 + DWR 防潑水技術處理\r\n關鍵部位接縫膠條 (壓膠) 處理\r\nShell Design\r\nAir-Flo™ 網狀拉鍊腿部內側通風口\r\n雪衣褲連接系統\r\n500D 馬蹄形下擺™\r\n褲管鞋帶花邊金屬鉤\r\n鈕扣褲管擴張系統\r\n皮帶環上的纜車票孔眼', '2025-02-23 14:02:27', NULL, NULL, NULL),
(14, '686 Men\'s Standard Shell Pant 滑雪褲 - Iron Maiden', 7700, 7, 1, '686 的基本款滑雪褲採用時尚的黑色配色，防水等級為 10K，為山區的惡劣條件提供有力的保護。而大腿內側的 Air-flo 網狀通風孔可在你感到悶熱時讓冷空氣進入調節。\r\n\r\n【 英國知名重金屬樂團 Iron Maiden 聯名款式 】', '10,000MM 防水等級 + DWR 防潑水技術處理\r\ninfiDRY® 10K 專利防水面料 + DWR 防潑水技術處理\r\n關鍵部位接縫膠條 (壓膠) 處理\r\nShell Design\r\nAir-Flo™ 網狀拉鍊腿部內側通風口\r\n雪衣褲連接系統\r\n500D 馬蹄形下擺™\r\n褲管鞋帶花邊金屬鉤\r\n鈕扣褲管擴張系統\r\n皮帶環上的纜車票孔眼', '2025-02-23 14:06:04', NULL, NULL, NULL),
(15, '686 Men\'s Standard Shell Pant 滑雪褲 - Tobacco', 4400, 7, 1, '686 的基本款滑雪褲採用時尚的黑色配色，防水等級為 10K，為山區的惡劣條件提供有力的保護。而大腿內側的 Air-flo 網狀通風孔可在你感到悶熱時讓冷空氣進入調節。', '10,000MM 防水等級 + DWR 防潑水技術處理\r\ninfiDRY® 10K 專利防水面料 + DWR 防潑水技術處理\r\n關鍵部位接縫膠條 (壓膠) 處理\r\nShell Design\r\nAir-Flo™ 網狀拉鍊腿部內側通風口\r\n雪衣褲連接系統\r\n500D 馬蹄形下擺™\r\n褲管鞋帶花邊金屬鉤\r\n鈕扣褲管擴張系統\r\n皮帶環上的纜車票孔眼', '2025-02-23 14:08:35', NULL, NULL, NULL),
(16, '686 Women\'s Standard Shell Pant 滑雪褲 - Black', 4400, 8, 2, '686 的基本款滑雪褲採用時尚的黑色配色，防水等級為 10K，為山區的惡劣條件提供有力的保護。而大腿內側的 Air-flo 網狀通風孔可在你感到悶熱時讓冷空氣進入調節。', '10,000MM 防水等級 + DWR 防潑水技術處理\r\ninfiDRY® 10K 專利防水面料 + DWR 防潑水技術處理\r\n關鍵部位接縫膠條 (壓膠) 處理\r\nShell Design\r\nAir-Flo™ 網狀拉鍊腿部內側通風口\r\n雪衣褲連接系統\r\n500D 馬蹄形下擺™\r\n褲管鞋帶花邊金屬鉤\r\n鈕扣褲管擴張系統\r\n皮帶環上的纜車票孔眼', '2025-02-23 14:11:16', NULL, NULL, NULL),
(17, '686 Women\'s Standard Shell Pant 滑雪褲 - Light Grey', 4400, 8, 2, '686 的基本款滑雪褲採用時尚的黑色配色，防水等級為 10K，為山區的惡劣條件提供有力的保護。而大腿內側的 Air-flo 網狀通風孔可在你感到悶熱時讓冷空氣進入調節。', '10,000MM 防水等級 + DWR 防潑水技術處理\r\ninfiDRY® 10K 專利防水面料 + DWR 防潑水技術處理\r\n關鍵部位接縫膠條 (壓膠) 處理\r\nShell Design\r\nAir-Flo™ 網狀拉鍊腿部內側通風口\r\n雪衣褲連接系統\r\n500D 馬蹄形下擺™\r\n褲管鞋帶花邊金屬鉤\r\n鈕扣褲管擴張系統\r\n皮帶環上的纜車票孔眼', '2025-02-23 14:14:00', NULL, NULL, NULL),
(18, '686 Women\'s Progression Padded Pant V2 內置防摔墊滑雪褲', 4400, 8, 2, '686 Progression 內置護墊滑雪褲，適合希望提高滑雪技能的滑雪者，它是一款符合人體工程學的低調防雪褲，配有可拆卸且貼合身體輪廓的襯墊，旨在在您摔倒時為您提供保護。膝蓋、大腿、臀部和切割 8 毫米的可拆卸 EVA 襯墊，以便於清潔，並在您撞擊的地方提供保護。', '膝蓋、大腿、臀部和座椅處採用全新可拆卸的切割 8 毫米 EVA 襯墊\r\n10,000MM 防水/透氣等級 + DWR 防潑水技術處理\r\ninfiDRY® 10K 專利尼龍防水面料 + DWR 防潑水技術處理\r\n關鍵部位的接縫膠條 (壓膠) 處理\r\n外部調節鬆緊彈性腰帶\r\nAir-Flo™ 網狀拉鍊腿部內側通風口\r\n雪衣褲連接系統\r\n500D 馬蹄形下擺™\r\n500D 膝蓋部位布料\r\n褲管鞋帶花邊金屬鉤\r\n皮帶環上的纜車票孔眼', '2025-02-23 14:16:24', NULL, NULL, NULL),
(19, 'Eb\'s XRD® Beanie 防護型毛帽 - Black', 1280, 2, 0, '後腦勺配備「XRD®」護墊的無簷毛帽', '分段式 XRD® 墊可吸收並減少對後腦勺的衝擊力。\r\n護墊無法移除。\r\n材質 ：100% 亞克力纖維\r\n \r\n\r\nXRD® 材質優勢 : \r\n\r\n吸收高達 90% 的撞擊衝擊力\r\n外部襯墊的防滑設計，避免因衝擊所造成襯墊位移\r\n高彈力面料，提供舒適、合身的貼合感\r\nMicroban® 抗菌技術提供持久抗菌保護，效果不會因清洗或磨損而消耗\r\n使用壽命長，耐久度高，並不會因高使用頻率下擠壓變形', '2025-02-23 14:23:22', NULL, NULL, NULL),
(20, 'SpecialGuest V2 Logo Beanie 毛帽 - Apple Green', 1000, 2, 0, 'SpecialGuest V2 Logo Beanie 毛帽', 'Shell Acrylic 100%', '2025-02-23 14:26:24', NULL, NULL, NULL),
(21, 'SpecialGuest V2 Logo Beanie 毛帽 - Black', 1000, 2, 0, 'SpecialGuest V2 Logo Beanie 毛帽', 'Shell Acrylic 100%', '2025-02-23 14:28:07', NULL, NULL, NULL),
(22, 'SpecialGuest Easy Beanie R 毛帽 - Pink Yarrow', 1200, 2, 0, 'SpecialGuest V2 Logo Beanie 毛帽', 'Shell Acrylic 100%', '2025-02-23 14:29:32', NULL, NULL, NULL),
(23, 'Burton Plush Beanie 毛帽 - Imperial Purple', 1300, 2, 0, '你值得擁有一頂毛絨玩具。\r\n除了舒適之外，還有 Burton 毛絨無簷毛帽。是那種一定能讓寒冷的冬天變得明亮的舒適感。', '70% 再生聚酯纖維、30% 聚酯纖維\r\n再生材料 : 至少 70% 的回收材料可減少對原材料和地球的影響。\r\n中筒款式 : 介於低筒無簷毛帽和高筒無簷毛帽之間的折衷方案。\r\n繡花補丁\r\n折疊式帽簷\r\n單一尺寸 One Size', '2025-02-23 14:31:15', NULL, NULL, NULL),
(24, 'Burton [ak] Stagger Beanie 毛帽 - Kelp', 1700, 2, 0, '無論是山上還是山下，Burton [ak] Stagger Beanie 均採用美麗諾羊毛製成，可調節溫度，讓您倍感舒適。', '65% 美麗諾羊毛，35% 尼龍\r\n輕盈美麗諾羊毛混紡面料為您提供自然溫度調節、透氣性和無異味的保暖效果。\r\n中筒款式 : 介於低筒無簷毛帽和高筒無簷毛帽之間的折衷方案。\r\n帽簷折疊設計，Skully Fit\r\n單一尺寸 One Size', '2025-02-23 14:33:26', NULL, NULL, NULL),
(25, 'Spyder Groomers Beanie 毛帽 - Aether Blue', 1300, 2, 0, 'Groomers 毛帽採用經典輪廓，是一款無襯裡、100% 再生聚酯纖維帽子，採用雙層結構製成，並配有 Spyder 刺繡貼片。', '100%再生聚酯紗\r\n無襯裡雙層結構\r\nSpyder 刺繡貼片', '2025-02-23 14:34:37', NULL, NULL, NULL),
(26, 'Spyder Shelby Beanie 毛帽 - True Navy', 1300, 2, 0, 'Spyder Shelby Beanie 毛帽', '100% 再生聚酯紗線\r\n抓絨襯裡\r\n針織 Logo 標誌設計\r\nOne Size 單一尺寸', '2025-02-23 14:36:54', NULL, NULL, NULL),
(27, 'Spyder Reversible Innsbruck Beanie 雙面毛帽 - Aether Blue', 1100, 2, 0, 'Spyder Reversible Innsbruck Beanie 雙面毛帽', '100%再生聚酯織線\r\n無襯裡雙層結構\r\n針織 Logo 設計\r\nOne Size 單一尺寸', '2025-02-23 14:38:23', NULL, NULL, NULL),
(28, 'Burton Men\'s Photon Step On® Boots 24/25 男款雪鞋 - Petrol Green', 16500, 10, 1, '只要一踩上去，即可盡情滑雪的探索樂趣。\r\nBurton Photon Step On® 的快速鎖定滿足 Step On® 的便利性。完美貼合和反應靈敏的感覺鼓勵您嘗試大膽的滑行風格。\r\n從 Step On® 的容易上手性到任何級別騎手所需的支撐性，當您需要在板上做更多事情時，Photon 都會為您提供支援。這是一款沒有什麼限制的靴子，無論是貼合度還是舒適度，都是為喜歡挑戰極限的騎手打造的。', 'Lacing : Sequence Boa®\r\nLiner : Imprint™ 3 Liner\r\nInner Cuff : Focus Cuff\r\nOutsole\r\nVibram Traction Lug\r\nVibram® EcoStep\r\nWarmth Features : Sleeping Bag Reflective Foil\r\nWarranty : 1-Year Warranty\r\nTerrain\r\nAll Mountain\r\nPark\r\nBackcountry', '2025-02-23 14:41:52', NULL, NULL, NULL),
(29, 'Burton Men\'s Photon Step On® Wide Boots 24/25 男款雪鞋 - Deep Emerald', 16500, 10, 1, '只要一踩上去，即可盡情滑雪的探索樂趣。\r\nBurton Photon Step On® 的快速鎖定滿足 Step On® 的便利性。完美貼合和反應靈敏的感覺鼓勵您嘗試大膽的滑行風格。\r\n從 Step On® 的容易上手性到任何級別騎手所需的支撐性，當您需要在板上做更多事情時，Photon 都會為您提供支援。這是一款沒有什麼限制的靴子，無論是貼合度還是舒適度，都是為喜歡挑戰極限的騎手打造的。', 'Lacing : Sequence Boa®\r\nLiner : Imprint™ 3 Liner\r\nInner Cuff : Focus Cuff\r\nOutsole\r\nVibram Traction Lug\r\nVibram® EcoStep\r\nWarmth Features : Sleeping Bag Reflective Foil\r\nWarranty : 1-Year Warranty\r\nTerrain\r\nAll Mountain\r\nPark\r\nBackcountry', '2025-02-23 14:51:28', NULL, '2025-02-25 09:08:34', NULL),
(30, 'Burton Men\'s Ruler Step On® Boots 24/25 男款雪鞋 - Black', 12500, 10, 1, '穿上這款 Burton Ruler Step On® 單板滑雪靴，可完成更大的坡度落差和增強你的滑雪技巧。\r\nRuler Step On® 秉持將個人技能提升至專業水平的傳統，將響應性能與 Step On® 的便利性相結合，打造出同樣靈活且強大耐用的雪靴。微調貼合度增添了輕鬆和像是飛行的體驗。', 'Lacing : Sequence Boa®\r\nLiner : Imprint™ 2\r\nInner Cuff : Lock-Up Cuff\r\nOutsole\r\nStep On™ Outsole\r\nBurton Recycled Content Rubber\r\nWarmth Features\r\n3M™ Thinsulate™ Insulation\r\nSleeping Bag Reflective Foil\r\nWarranty :1-Year Warranty\r\nTerrain\r\nAll Mountain\r\nPark', '2025-02-23 14:54:57', NULL, NULL, NULL),
(31, 'Burton Men\'s Ruler Step On® Boots 男款雪鞋 24/25 - Gray Cloud', 12500, 10, 1, '穿上這款 Burton Ruler Step On® 單板滑雪靴，可完成更大的坡度落差和增強你的滑雪技巧。\r\nRuler Step On® 秉持將個人技能提升至專業水平的傳統，將響應性能與 Step On® 的便利性相結合，打造出同樣靈活且強大耐用的雪靴。微調貼合度增添了輕鬆和像是飛行的體驗。', 'Lacing : Sequence Boa®\r\nLiner : Imprint™ 2\r\nInner Cuff : Lock-Up Cuff\r\nOutsole\r\nStep On™ Outsole\r\nBurton Recycled Content Rubber\r\nWarmth Features\r\n3M™ Thinsulate™ Insulation\r\nSleeping Bag Reflective Foil\r\nWarranty :1-Year Warranty\r\nTerrain\r\nAll Mountain\r\nPark', '2025-02-23 14:58:55', NULL, NULL, NULL),
(32, 'Burton Men\'s Ruler Step On® Boots 男款雪鞋 24/25 - Goldenrod', 12500, 10, 1, '穿上這款 Burton Ruler Step On® 單板滑雪靴，可完成更大的坡度落差和增強你的滑雪技巧。\r\nRuler Step On® 秉持將個人技能提升至專業水平的傳統，將響應性能與 Step On® 的便利性相結合，打造出同樣靈活且強大耐用的雪靴。微調貼合度增添了輕鬆和像是飛行的體驗。', 'Lacing : Sequence Boa®\r\nLiner : Imprint™ 2\r\nInner Cuff : Lock-Up Cuff\r\nOutsole\r\nStep On™ Outsole\r\nBurton Recycled Content Rubber\r\nWarmth Features\r\n3M™ Thinsulate™ Insulation\r\nSleeping Bag Reflective Foil\r\nWarranty :1-Year Warranty\r\nTerrain\r\nAll Mountain\r\nPark', '2025-02-23 15:02:30', NULL, NULL, NULL),
(33, 'Burton Women\'s Felix Step On® Boots 24/25 女款雪鞋 - Petrol Green', 16500, 11, 2, '只要一踩上去，即可盡情滑雪的探索樂趣。更舒適且更具可調節性。\r\n當您穿著 Burton Felix Step On® 滑雪靴時，您唯一需要擔心的就是接下來要跑那條雪道。 除了我們的 Step On 固定器改變遊戲規則的簡單性之外，還配備了最新的技術，讓您的雙腳保持舒適，並具有微調貼合度，讓您從上到下都保持一致的貼合性。\r\n融入了充足反應的設計中，提供放鬆的姿勢和全地形多功能性。', 'Lacing : Boa®\r\nSupport : Medium - Stiff\r\nFeatures\r\nDRYRIDE Heat Cycle™\r\nEST® Sole\r\nStep On™\r\nWaste Reduction\r\nTerrain\r\nAll Mountain\r\nPark\r\nBackcountry', '2025-02-23 15:09:04', NULL, NULL, NULL),
(34, 'Burton Women\'s Felix Step On® Wide Boots 24/25 女款雪鞋 - Black\r\n', 16500, 11, 2, '只要一踩上去，即可盡情滑雪的探索樂趣。更舒適且更具可調節性。\r\n當您穿著 Burton Felix Step On® 滑雪靴時，您唯一需要擔心的就是接下來要跑那條雪道。 除了我們的 Step On 固定器改變遊戲規則的簡單性之外，還配備了最新的技術，讓您的雙腳保持舒適，並具有微調貼合度，讓您從上到下都保持一致的貼合性。\r\n融入了充足反應的設計中，提供放鬆的姿勢和全地形多功能性。', 'Lacing : Boa®\r\nSupport : Medium - Stiff\r\nFeatures\r\nDRYRIDE Heat Cycle™\r\nEST® Sole\r\nStep On™\r\nWaste Reduction\r\nTerrain\r\nAll Mountain\r\nPark\r\nBackcountry', '2025-02-23 15:12:30', NULL, NULL, NULL),
(35, 'Burton Women\'s Felix Step On® Wide Boots 24/25 女款雪鞋 - Goldenrod', 16500, 11, 2, '只要一踩上去，即可盡情滑雪的探索樂趣。更舒適且更具可調節性。\r\n當您穿著 Burton Felix Step On® 滑雪靴時，您唯一需要擔心的就是接下來要跑那條雪道。 除了我們的 Step On 固定器改變遊戲規則的簡單性之外，還配備了最新的技術，讓您的雙腳保持舒適，並具有微調貼合度，讓您從上到下都保持一致的貼合性。\r\n融入了充足反應的設計中，提供放鬆的姿勢和全地形多功能性。', 'Lacing : Boa®\r\nSupport : Medium - Stiff\r\nFeatures\r\nDRYRIDE Heat Cycle™\r\nEST® Sole\r\nStep On™\r\nWaste Reduction\r\nTerrain\r\nAll Mountain\r\nPark\r\nBackcountry', '2025-02-23 15:15:25', NULL, NULL, NULL),
(36, 'Burton Women\'s Limelight Step On® Wide Boots 24/25 女款雪鞋 - Gray Cloud', 12400, 11, 2, '讓一切看起來更輕鬆，只要一踩上去，即可盡情滑雪的探索樂趣。\r\n這正是 Limelight Step On® 單板滑雪靴的特色，讓您開箱即用，享受雙腳的舒適體驗，輕鬆度過一天。它們平衡了全天的舒適感和輕鬆的感覺，實現了多功能性能。 Step On® 系統的直覺連接可實現乾淨的穿脫體驗和一致的雪板控制。\r\n保暖、熱塑型內襯與熱反射技術相結合，帶來一流的溫暖舒適感。', 'Lacing : Sequence Boa®\r\nLiner : Imprint™ 2\r\nInner Cuff : Lock-Up Cuff\r\nOutsole\r\nStep On™ Outsole\r\nBurton Recycled Content Rubber\r\nWarmth Features\r\n3M™ Thinsulate™ Insulation\r\nSleeping Bag Reflective Foil\r\nWarranty : 1-Year Warranty\r\nTerrain\r\nAll Mountain\r\nPark\r\n', '2025-02-23 15:18:38', NULL, NULL, NULL),
(37, 'Burton Women\'s Felix BOA® Boots 24/25 女款雪鞋 - Petrol Green', 15900, 11, 2, '當您穿著 Burton Felix BOA® 滑雪靴時，您唯一需要擔心的就是接下來要跑哪條路線。\r\n它們採用了讓您保持溫暖和乾燥的技術，並具有雙顆 BOA® 牢固固定的微調貼合度，讓您可以調節鞋面和鞋面的感覺以匹配您的雙腳。這一切都融入了靈活的設計中，保持放鬆的姿勢和全地形多功能性。', 'Lacing : Dual Zone BOA® Lockdown\r\nSupport : Medium - Stiff\r\nFeatures\r\nDRYRIDE Heat Cycle™\r\nEST® Sole\r\nWaste Reduction\r\nInner Cuff\r\nFocus Cuff\r\nOutsole\r\nVibram® Traction Lug Outsole\r\nVibram® EcoStep\r\nWarmth Features\r\nSleeping Bag Reflective Foil\r\nTerrain\r\nAll Mountain\r\nPark\r\nBackcountry', '2025-02-23 15:22:22', NULL, NULL, NULL),
(38, 'Burton Men\'s Process Flying V Snowboard 24/25 滑雪板', 19200, 15, 1, '這款對稱板型滑雪板可在您需要時提供動力，彰顯 Burton 團隊騎手 Mark McMorris 的輕鬆風格。\r\nMark McMorris 選擇了 Burton Process 滑雪板，因為它兼具 Freestyle 樂趣和全地形能力。準備起飛的板身為您提供充足的 Pop 和 Flying V Camber 的精確控制能力。且今年將老虎的輕鬆駕馭力量的悠然自得帶到了同樣充滿力量的這款雪版上。', 'Flying V™\r\n\r\n具有兩腳之間和雙腳外側的ROCKER輪廓，可增加雪板的樂趣；腳下CAMBER輪廓在滑行時增加鋼邊控制力，精準的控制、增加彈力和強而有力的轉向。\r\n\r\nTwin Shape\r\n\r\nTwin Shape 完全對稱，因此無論您是正常滑行還是Switch 滑行，都擁有出色的穩定性旋轉和相同感受。\r\n\r\n \r\n\r\n\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容\r\n\r\nTwin Flex\r\n\r\n完全對稱的雪板彈性，無論是常規雪道滑行或是Switch，在表現上達成完美平衡的多功能性。\r\n\r\n\r\n\r\nTriax™ Fiberglass\r\n\r\nTriax 玻璃纖維，同時提供雪板各處所需的強度和響應，並採用超輕碳纖骨架，以增加彈力和縱向強度。\r\n\r\nSintered Base\r\n\r\n耐用且板底毛細孔密集，提供額外的耐用性和卓越的吸蠟性，從而實現更好的滑動能力。', '2025-02-23 15:45:26', NULL, NULL, NULL),
(39, 'Burton Men\'s Custom X Camber Snowboard 24/25 滑雪板', 29400, 15, 1, 'Burton 系列中最具侵略性的雪板，具有專業級的速度和精確度。\r\n專業級對於任何滑雪板來說都是一個強有力的口碑象徵，Custom X 憑藉精細的設計和強大的驅動力，多次為最刁鑽的騎手提供服務。\r\n我們對這張雪板技術充滿信心，其中包括 Carbon-fueled 的 Squeezebox High 核心、競賽級底座和 45° 碳纖High-Voltage，實現終極輕量化響應。', 'Camber\r\n\r\nCamber 提倡強大的轉彎能量和精度，提供靈活的拱形設計，重量均勻分佈在整個板上，以實現從尖端到尾部的平滑、連續的鋼邊控制\r\n\r\nAll Mountain Directional Shape\r\n\r\n經典的滑雪板形狀，設計時板頭比板尾稍長，以便將彈力集中在尾部，同時提供充足的浮力、流動和控制力，以適應任何地形或條件。\r\n\r\n\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容\r\n\r\nTwin Flex\r\n\r\n完全對稱的雪板彈性，無論是常規雪道滑行或是Switch，在表現上達成完美平衡的多功能性。\r\n\r\n\r\n\r\nDragonfly™ 600G Core\r\n\r\n採用 Multizone™ EGD™，在衝擊區使用端粒木材，在不犧牲強度的情況下減輕重量。\r\n\r\nMultizone™ EGD™\r\n\r\n在衝擊區使用端粒木材，在不犧牲強度的情況下減輕重量。\r\n\r\n\r\n\r\nCarbon Highlights\r\n\r\n45° 碳纖維和玻璃纖維構造優化了玻璃纖維基質的每一層，從頭到尾添加了完整的碳纖層，以減輕重量並微調扭轉雪板的感覺。\r\n\r\nSintered WFO Base\r\n\r\n將特殊配方的板底蠟注入超吸水性高密度再生燒結材料的孔隙深處，使任何條件環境下的滑行表現一致且超耐久。', '2025-02-23 15:50:11', NULL, NULL, NULL),
(40, 'Burton Men\'s Deep Thinker Camber Snowboard 24/25 滑雪板', 22800, 15, 1, 'Burton Deep Thinker 滑雪板是職業滑雪者 Danny Davis 最愛在 Park,Pipe 或 mobbing 中使用的指向性滑雪板。\r\n幾何設計的獨特形狀，加上指向型 Camber 的浮力和響應能力，只需一點錐度即可提高它的全山能力，同時保持 Freeride 的爆發性，45° 碳纖維提供輕鬆的彈跳力，卻沒有僵硬的副作用。', 'Directional Camber\r\n\r\n在雙腳下方具有Camber輪廓，可在較深的轉彎和各種地形條件下保持穩定性，並且rocker板頭可增加浮力。\r\n\r\nAll Mountain Directional Shape\r\n\r\n經典的滑雪板形狀，設計時板頭比板尾稍長，以便將彈力集中在尾部，同時提供充足的浮力、流動和控制力，以適應任何地形或條件。\r\n\r\n\r\n\r\n7mm Taper\r\n\r\n7 mm Taper 使轉彎變得更輕鬆，提供指向性雪板的優勢和感覺，同時又像對稱板一樣沒有任何阻礙的滑行感受。\r\n\r\nDirectional Flex\r\n\r\nDirectional Flex 在板尾增加彈力和更具彈性的板頭，使騎手能夠在所有地形和條件下輕鬆保持控制。\r\n\r\n\r\n\r\nSuper Fly II™ 700G Core\r\n\r\n使用更堅固、更輕的木材來提供彈力和強度，同時減輕整體重量\r\n\r\nDualzone™ EGD™\r\n\r\nDualzone™ EGD™ 木紋 沿著腳尖和腳跟鋼邊的位置垂直於雪板核心上，達成更優秀的edge-hold、響應和強度。\r\n\r\n\r\n\r\nCarbon Highlights\r\n\r\n45° 碳纖維和玻璃纖維構造優化了玻璃纖維基質的每一層，從頭到尾添加了完整的碳纖層，以減輕重量並微調扭轉雪板的感覺。\r\n\r\nSintered WFO Base\r\n\r\n將特殊配方的板底蠟注入超吸水性高密度再生燒結材料的孔隙深處，使任何條件環境下的滑行表現一致且超耐久。\r\n\r\n\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容\r\n\r\nDragonfly™ 600G Core\r\n\r\n採用 Multizone™ EGD™，在衝擊區使用端粒木材，在不犧牲強度的情況下減輕重量。\r\n\r\nMultizone™ EGD™\r\n\r\n在衝擊區使用端粒木材，在不犧牲強度的情況下減輕重量。\r\n\r\n\r\n\r\nCarbon Highlights\r\n\r\n45° 碳纖維和玻璃纖維構造優化了玻璃纖維基質的每一層，從頭到尾添加了完整的碳纖層，以減輕重量並微調扭轉雪板的感覺。\r\n\r\nSintered WFO Base\r\n\r\n將特殊配方的板底蠟注入超吸水性高密度再生燒結材料的孔隙深處，使任何條件環境下的滑行表現一致且超耐久。', '2025-02-23 15:56:07', NULL, NULL, NULL),
(41, 'Burton Men\'s Ripcord Flat Top Snowboard 24/25 滑雪板', 14200, 15, 1, '我們最精簡、最適合初學進步的滑雪板。\r\nBurton Ripcord 滑雪板旨在幫助初學者和中級滑雪者加速進入更進階的滑行環境。指向形狀使您可以在任何地形或雪況下輕鬆滑行，而帶有 Easy Bevel flat輪廓增加了穩定性和無卡邊感。\r\n更柔軟、更有趣的靈活性使其成為其他對稱板的替代品，以性能為導向的滑行為您提供比大多數入門級雪板更多的成長空間。', 'Flat Top\r\n\r\n提供穩定性、平衡和連續的鋼邊控制，有助於板頭和板尾抬起，實現無卡邊和輕鬆的滑行體驗。\r\n\r\nAll Mountain Directional Shape\r\n\r\n經典的滑雪板形狀，設計時板頭比板尾稍長，以便將彈力集中在尾部，同時提供充足的浮力、流動和控制力，以適應任何地形或條件。\r\n\r\n\r\n\r\n5mm Taper\r\n\r\n使轉彎變得更輕鬆，提供指向性雪板的優勢和感覺，同時又像對稱板一樣沒有任何阻礙的滑行感受。\r\n\r\nDirectional Flex\r\n\r\nDirectional Flex 在板尾增加彈力和更具彈性的板頭，使騎手能夠在所有地形和條件下輕鬆保持控制。\r\n\r\n\r\n\r\nFly® 900G Core\r\n\r\n一款經典的從頭到尾的木芯，它利用兩種木材中的優點來減輕負載，而不犧牲柔韌性、彈力或強度。\r\n\r\nBiax™ Fiberglass\r\n\r\nBiax 玻璃纖維具有對 JIB 友好、扭轉柔軟的特性和容易操控的感覺，非常適合初學者或Park。\r\n\r\n\r\n\r\nExtruded Base\r\n\r\n提供速度和強度，並且幾乎不需要維護即可擁有良好的滑行體驗。\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容。\r\n\r\n', '2025-02-23 16:00:15', NULL, NULL, NULL),
(42, 'Burton Unisex 3D Fish Directional Flat Top Snowboard 24/25 滑雪板', 24500, 20, 3, '踏上這款受衝浪啟發的粉雪板，專為雪山上最深處的地形而設計。\r\nBurton Fish 3D 滑雪板以我們標誌性 Fish 設計的形狀為基礎，在尖端和尾部添加了受衝浪板啟發的 3D 凸形形狀。使 Fish 在深雪中的衝浪能力、響應能力和控制能力達到了新的水平。\r\n它是度過最深的粉雪氣候和無人探索的秘密基地的首選工具。 雙燕尾增加了速度和轉彎控制，同時減少長度使滑行更加靈活。', 'Directional Flat Top\r\n\r\n具有整體平坦的板型輪廓，且板頭帶有Rocker ，可實現穩定性和輕鬆漂浮，非常適合在粉雪地形上的衝浪日\r\n\r\nAll Mountain Directional Shape\r\n\r\n經典的滑雪板形狀，設計時板頭比板尾稍長，以便將彈力集中在尾部，同時提供充足的浮力、流動和控制力，以適應任何地形或條件。\r\n\r\n\r\n\r\n30mm Taper\r\n\r\n30 mm 的 Taper 可增加浮力和轉彎能力，尾部寬度較短，可增加下壓力，且板頭處寬度較寬，有助於板頭 pop up.\r\n\r\nDirectional Flex\r\n\r\nDirectional Flex 在板尾增加彈力和更具彈性的板頭，使騎手能夠在所有地形和條件下輕鬆保持控制。\r\n\r\n\r\n\r\nSuper Fly II™ 700G Core\r\n\r\n使用更堅固、更輕的木材來提供彈力和強度，同時減輕整體重量\r\n\r\nDualzone™ EGD™\r\n\r\nDualzone™ EGD™ 木紋 沿著腳尖和腳跟鋼邊的位置垂直於雪板核心上，達成更優秀的edge-hold、響應和強度。\r\n\r\n\r\n\r\nCarbon Highlights\r\n\r\n45° 碳纖維和玻璃纖維構造優化了玻璃纖維基質的每一層，從頭到尾添加了完整的碳纖層，以減輕重量並微調扭轉雪板的感覺。\r\n\r\nSintered WFO Base\r\n\r\n將特殊配方的板底蠟注入超吸水性高密度再生燒結材料的孔隙深處，使任何條件環境下的滑行表現一致且超耐久。', '2025-02-23 16:04:18', NULL, NULL, NULL),
(43, 'Burton Unisex Good Company Camber Snowboard 24/25 滑雪板', 15300, 20, 3, '久經考驗的真正雙胞胎，經典永遠是最好的選擇。\r\nBurton Good Company Camber 滑雪板是一款傳統的 Camber 對稱滑雪板，適合尋求在所有地形中都能發揮作用的標準板形和保持傳統感覺的彈性。它是一種精緻的結構，平衡了力量、速度和彈跳性，適合在山上的任何地方追擊和跺腳落地。', 'Camber\r\n\r\nCamber 提倡強大的轉彎能量和精度，提供靈活的拱形設計，重量均勻分佈在整個板上，以實現從尖端到尾部的平滑、連續的鋼邊控制\r\n\r\nTwin Shape\r\n\r\nTwin Shape 完全對稱，因此無論您是正常滑行還是Switch 滑行，都擁有出色的穩定性旋轉和相同感受。\r\n\r\n\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容\r\n\r\nTwin Flex\r\n\r\n完全對稱的雪板彈性，無論是常規雪道滑行或是Switch，在表現上達成完美平衡的多功能性。\r\n\r\n\r\n\r\nTriax™ Fiberglass\r\n\r\nTriax 玻璃纖維，同時提供雪板各處所需的強度和響應，並採用超輕碳纖骨架，以增加彈力和縱向強度。\r\n\r\nSintered Base\r\n\r\n耐用且板底毛細孔密集，提供額外的耐用性和卓越的吸蠟性，從而實現更好的滑動能力。', '2025-02-23 16:08:28', NULL, NULL, NULL),
(44, 'Burton Women\'s Stylus Rocker Snowboard 24/25 滑雪板', 14200, 16, 2, 'Burton Stylus 滑雪板是女士系列中最適合初學的滑雪板，專為希望建立技能基礎的有抱負的騎手而設計。\r\n就像把筆放在一張白紙上一樣，Stylus 可以消除您的恐懼，從您第一次繫好安全帶時就開始傳授平衡和雪板控制，帶來輕鬆的感覺、高容錯靈活性和自由的滑行體驗。無論您指向哪個方向，它都穩定且易於操作。', 'V-Rocker™\r\n\r\nV 型 Rocker 位於中間，固定器下方有 Flat 區域，固定器區域外有連續 Rocker，營造出輕鬆騎乘、衝浪的感覺。\r\n\r\nTwin Shape\r\n\r\nTwin Shape 完全對稱，因此無論您是正常滑行還是Switch 滑行，都擁有出色的穩定性旋轉和相同感受。\r\n\r\n \r\n\r\n\r\n\r\nTwin Flex\r\n\r\n完全對稱的雪板彈性，無論是常規雪道滑行或是Switch，在表現上達成完美平衡的多功能性。\r\n\r\nBiax™ Fiberglass\r\n\r\nBiax 玻璃纖維具有對 JIB 友好、扭轉柔軟的特性和容易操控的感覺，非常適合初學者或Park。\r\n\r\n\r\n\r\nExtruded Base\r\n\r\n提供速度和強度，並且幾乎不需要維護即可擁有良好的滑行體驗。\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容。', '2025-02-23 19:39:36', NULL, NULL, NULL),
(45, 'Burton Women\'s Feelgood Camber Snowboard 24/25 滑雪板', 21800, 16, 2, '當您想要逐雪刻滑並探索自然樹林時，Burton Feelgood 滑雪板將助您取得成功。\r\n在團隊騎手 Kelly Clark 的支持下，它擁有獨特的形狀，與 Camber 輪廓相匹配，並且具有法拉利般的強勁操控性。指向型板型可輕鬆應對各種條件，使其成為征服所有地形的首選板。', 'Camber\r\n\r\nCamber 提倡強大的轉彎能量和精度，提供靈活的拱形設計，重量均勻分佈在整個板上，以實現從尖端到尾部的平滑、連續的鋼邊控制\r\n\r\nAll Mountain Directional Shape\r\n\r\n經典的滑雪板形狀，設計時板頭比板尾稍長，以便將彈力集中在尾部，同時提供充足的浮力、流動和控制力，以適應任何地形或條件。\r\n\r\n\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容\r\n\r\nTwin Flex\r\n\r\n完全對稱的雪板彈性，無論是常規雪道滑行或是Switch，在表現上達成完美平衡的多功能性。\r\n\r\n\r\n\r\nCarbon Highlights\r\n\r\n45° 碳纖維和玻璃纖維構造優化了玻璃纖維基質的每一層，從頭到尾添加了完整的碳纖層，以減輕重量並微調扭轉雪板的感覺。\r\n\r\nSintered WFO Base\r\n\r\n將特殊配方的板底蠟注入超吸水性高密度再生燒結材料的孔隙深處，使任何條件環境下的滑行表現一致且超耐久。', '2025-02-23 19:45:54', NULL, NULL, NULL),
(46, 'Burton Women\'s Yeasayer Flying V Snowboard 24/25 滑雪板', 17800, 16, 2, '從未經探索的雪山到您最喜歡的公園，Burton Yeasayer 滑雪板可以馴服任何阻礙您的事物。\r\nFlying V 的輪廓設計提供了一種輕鬆、飄逸的感覺，對稱設計讓您無論朝哪個方向都可以掌控。無論您是在及膝深的深雪中衝浪，都能拉升板頭，帶來無束縛的感覺。', 'Flying V™\r\n\r\n具有兩腳之間和雙腳外側的ROCKER輪廓，可增加雪板的樂趣；腳下CAMBER輪廓在滑行時增加鋼邊控制力，精準的控制、增加彈力和強而有力的轉向。\r\n\r\nTwin Shape\r\n\r\nTwin Shape 完全對稱，因此無論您是正常滑行還是Switch 滑行，都擁有出色的穩定性旋轉和相同感受。\r\n\r\n \r\n\r\n\r\n\r\nThe Channel®\r\n\r\nChannel® 雪板追求最細緻完美的站姿寬度，並與所有雪板固定器兼容\r\n\r\nTwin Flex\r\n\r\n完全對稱的雪板彈性，無論是常規雪道滑行或是Switch，在表現上達成完美平衡的多功能性。\r\n\r\n\r\n\r\nTriax™ Fiberglass\r\n\r\nTriax 玻璃纖維，同時提供雪板各處所需的強度和響應，並採用超輕碳纖骨架，以增加彈力和縱向強度。\r\n\r\nExtruded Base\r\n\r\n提供速度和強度，並且幾乎不需要維護即可擁有良好的滑行體驗。', '2025-02-23 19:49:01', NULL, NULL, NULL),
(47, 'K2 LUV 75 Women\'s Ski 雙板滑雪板（套裝）', 19280, 14, 2, 'Easy to Maneuver\r\n雪板組包含可調式固定器', 'Fall in luv with skiing all over again on the K2 Luv 75. Forgiving and easy to maneuver, this ski\'s Catch-Free Rocker and ultra-light composite core keep your legs fresher than morning yoga. Softly rounded tip and tail ease into turns to remind you how much fun it is to fly downhill any season, and classic cap construction ties this delicious piece together – the Luv 75 is the complete package for all-mountain explorers.\r\nRadius:\r\n14m @163\r\n \r\nConstruction:\r\nComposite Core\r\n \r\nBinding Options:\r\nMarker K2 / ER3 10.0\r\n \r\nFeatures:\r\nCap Construction\r\n \r\nBaseline:\r\nCatch-Free Rocker\r\n \r\nDimensions:\r\n115/75/106\r\n \r\nSizes Offered:\r\n142, 149, 156, 163\r\nTechnology\r\nCap construction\r\nCap Construction\r\n\r\nDurable and lightweight 「cap」 skis are built by a sophisticated molding process that envelopes the core and internal materials with the top layer of the ski. Used throughout our ski line, cap constructions can be assembled with a variety of different cores. These variations, such as glass and/or metal materials, are the determining factors of the skis\' performance.', '2025-02-23 19:53:34', NULL, NULL, NULL),
(48, 'K2 LUVIT 76 Women\'s Ski 雙板滑雪板（套裝）', 26880, 14, 0, 'Ski With Your Heart\r\n雪板組包含可調式固定器', 'Radius:\r\n14m @163\r\n \r\nConstruction:\r\nComposite Core\r\n \r\nBinding Options:\r\nMarker K2 / ER3 10\r\n \r\nFeatures:\r\nHybritech Sidewall\r\n \r\nBaseline:\r\nAll-Terrain Rocker\r\n \r\nDimensions:\r\n120/76/105\r\n \r\nSizes Offered:\r\n142, 149, 156, 163', '2025-02-25 18:25:54', NULL, NULL, NULL),
(50, '【HEAD】Supershape e-Rally(PROTECTOR 13)_雙板滑雪板_2425', 36900, 14, 0, '因尖端設計、卓越工程和支持世界各地所有運動的熱情而享有盛譽，成為高山滑雪比賽和冬季奧運會上最成功的裝備品牌，提供專業運動員連續 12 年在雪道上奪得了冠軍！締造高山運動的歷史。', '- 128 / 78 / 112\r\n- 轉彎半徑：詳見下方規格說明\r\n- 使用EMC電子滑雪減震系統\r\n- Crossforce Carbon碳技術提供輕量和負載分佈的平衡\r\n- Better Balance Plate (SL 259 - 382 mm)\r\n- Worldcup 夾層結構\r\n- Speed Rocker\r\n- Race Structured UHM C底座\r\n- 固定器：PROTECTOR PR 13 GW Brake [P] 85 mm', '2025-02-26 14:01:25', NULL, NULL, NULL),
(51, 'Roxy Women\'s Gore-Tex Lunalite 3L Snow Jacket 滑雪外套 - Buttercream', 17800, 5, 0, '穿上我們的 ROXY Gore-Tex® Lunalite 3L 滑雪外套，保持溫暖和乾爽。\r\n採用環保面料、Gore-Tex 3L 防水透氣技術、DWR 防水面料處理、由回收 PET 瓶製成的 WarmFlight® 保暖材質、量身定制的剪裁和可調節兜帽。', '100% 再生聚酯平紋布料\r\nGORE-TEX® 防水透氣技術, 保證隨時保持乾爽 + 不含 PFC DWR 防水塗層處理\r\nWarmFlight® x1 保暖科技技術，由回收 PET 瓶製成，超輕且透氣保暖\r\nTailored fit 修身版型\r\nYKK® Aquaguard® 防水拉鍊設計\r\n相容於安全帽的可調式固定風帽，頂部附金屬絲遮陽板\r\n雙邊插手口袋\r\n胸前置物口袋\r\n內部手機口袋和護目鏡口袋\r\n袖口通行證口袋\r\n全部位壓膠接縫處理\r\n雪衣褲連結系統\r\n3D 彈性按扣式雪裙\r\n網狀襯裡腋下通風孔\r\n帶有拇指孔的內部彈力指套\r\n袖口魔鬼氈調節\r\n下巴穿孔遮風護罩\r\n鑰匙夾\r\n內附鏡片拭鏡布', '2025-02-27 13:33:29', NULL, NULL, NULL);

--
-- 已傾印資料表的索引
--

--
-- 資料表索引 `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`);

--
-- 在傾印的資料表使用自動遞增(AUTO_INCREMENT)
--

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;

--
-- 已傾印資料表的限制式
--

--
-- 資料表的限制式 `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
